name: test

on:
  pull_request: { }
  push: { }

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.16'
      - run: make test
